---
name: github-actions-sample-main.yml
#       10        20        30        40        50        60        70        80
# 3456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 
on: push

jobs:
  lint-job:
    name: Lint code
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run linter
        uses: github/super-linter@v7
        env: 
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_TOKEN }}

  build-job:
    name: Build web API
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/GitHubActionsWebApi
    strategy:
      matrix:
        dotnet-version: ['8.0.x']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          source-url: https://nuget.pkg.github.com/lmcwhirt-insight/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.PAT_GITHUB_TOKEN}}

      - name: Install GitVersion
        uses: GitTools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
          preferLatestVersion: true

      - name: Determine version
        id: gitversion
        uses: GitTools/actions/gitversion/execute@v0

      - name: Log gitversion output
        run: echo "gitversion.output:c ${{ toJSON(steps.gitversion.outputs) }}"

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release /p:Version=${{ format('{0}.{1}.{2}', steps.gitversion.outputs.major, steps.gitversion.outputs.minor, steps.gitversion.outputs.buildMetaData) }}

      - name: Test with the dotnet CLI
        run: dotnet test --no-restore --results-directory "TestResults-${{ matrix.dotnet-version }}"

      - name: Upload dotnet test results
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-test-results-${{ matrix.dotnet-version }}
          path: TestResults-${{ matrix.dotnet-version }}
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}      

      - name: Dotnet package
        run: dotnet pack --no-restore --configuration Release /p:PackageVersion=${{ format('{0}.{1}.{2}', steps.gitversion.outputs.major, steps.gitversion.outputs.minor, steps.gitversion.outputs.buildMetaData) }}
        
      - name: Dotnet publish
        run: dotnet nuget push ./bin/Release/*.nupkg --skip-duplicate
