---
name: github-actions-sample-main.yml

on: push

jobs:
  lint-job:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run linter
        uses: github/super-linter@v4
        env: 
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_TOKEN }}
  build-job:
    name: Build web API
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/GitHubActionsWebApi
    strategy:
      matrix:
        dotnet-version: [ '7.0.x' ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          source-url: https://nuget.pkg.github.com/lmcwhirt-insight/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.PAT_GITHUB_TOKEN}}
      - name: Get data
        run: echo "${{ secrets.PAT_GITHUB_TOKEN }}" > secret.txt && cat secret.txt
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test with the dotnet CLI
        run: dotnet test --no-restore --results-directory "TestResults-${{ matrix.dotnet-version }}"
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-test-results-${{ matrix.dotnet-version }}
          path: TestResults-${{ matrix.dotnet-version }}
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}      
      - name: Dotnet ackage
        run: dotnet pack --configuration Release --no-restore 
      - name: Publish the package to GPR
        run: dotnet nuget push ./bin/Release/*.nupkg
        